% uplink scenarion with qeyssat
clear variables
% clc

qrackling_dir = '../../Qrackling';
addpath(genpath(qrackling_dir))

qkd_wavelength = 785;
scheme = "uplink";

source = components.Source( ...
    qkd_wavelength,    ...
    'Repetition_Rate', 1e9, ...
    'MPN_Signal',      1    ...
);

%% Satellite
qeyssat_telescope = components.Telescope( ...
    0.25,              ...
    'Wavelength',      qkd_wavelength, ...
    'Pointing_Jitter', 1e-6            ...
);

MPD_BB84_detector = components.Detector( ...
    qkd_wavelength, ...
    1e9,            ...
    1e-9,           ...
    10,             ...
    'Preset',       components.loadPreset("MicroPhotonDevices") ...
);

uplink_camera = beacon.Camera( ...
    qeyssat_telescope ...
);
pass_time = datetime(2069,05,13,00,08,28, 'Format', 'yyyy_MM_dd_hh_mm_ss');
disp(pass_time)
sim_duration = 0.5;
start_time = pass_time - sim_duration / 2;
stop_time = pass_time + sim_duration / 2;

qeyssat = nodes.Satellite( ...
    qeyssat_telescope, ...
    'KeplerElements', [ ...
        6921000, ...
        0,       ...
        97.6,    ...
        167.4,   ...
        98.9170, ...
        60       ...
    ], ...
    'startTime',  start_time,        ...
    'stopTime',   stop_time,         ...
    'sampleTime', 1,                 ...
    'Name',       'QEYSSat',         ...
    'Camera',     uplink_camera      ...
);
if scheme == "uplink"
    qeyssat.Detector = MPD_BB84_detector;
else
    qeyssat.Source = source;
end

%% OGS

% disp(source)

hogs = HubOpticalGroundStation(qkd_wavelength);
if scheme == "uplink"
    hogs.Source = source;
else
    hogs.Detector = MPD_BB84_detector;
end

%% Environment
loc = which('nodes.Satellite');
[path, ~, ~] = fileparts(loc);
elems = strsplit(path, filesep);
path_root = string(join(elems(1:end-2), filesep)) + filesep;
whichSeparator = @(Path, Sep) Sep{cellfun(@(sep) contains(Path, sep), Sep)};
MakePathNative = @(Path) strjoin(strsplit(Path, whichSeparator(Path, {'/', '\'})), filesep);
brightness_data = load(path_root + MakePathNative("Examples/Data/measured background counts/HWU_Experimental_Sky_Brightness.mat")).data;

sky_brightness = permute(brightness_data.Spectral_Pointance,[3,1,2]);

sky_elevations = linspace(0, 90, 46);
sky_headings = linspace(0, 360, 91);

mapped_night_sky = environment.mapToEnvironment( ...
    brightness_data.Headings,   ...
    brightness_data.Elevations, ...
    sky_brightness,             ... %780nm is at index 1
    sky_headings,               ...
    sky_elevations,             ...
    "Wavelength",               brightness_data.Wavelengths ...
);

loc = which('utilities.readModtranFile');
[path, ~, ~] = fileparts(loc);
elems = strsplit(path, filesep);
path_root = string(join(elems(1:end-1), filesep)) + filesep;
example_path = "Examples/Data/atmospheric transmittance/varying elevation MODTRAN data 2/";
data_path = path_root + MakePathNative(example_path);
paths = dir(data_path);
FilterStrings = @(haystack, needle) haystack(arrayfun(@(h) contains(h, needle), haystack));
csv_files = FilterStrings({paths.name}, ".csv");
% disp(csv_files')

schema = {'data_type', 'visibility', 'visibility_label', 'zenith_label', 'zenith_angle', 'end'};
file_details = cellfun(@(f) cell2struct(split(f, "_"), schema), csv_files);
elevations = sort(str2double(replace({file_details.zenith_angle}, "deg", "")));
sorted_file_names = string( ...
    arrayfun( ...
        @(n) csv_files(contains(csv_files, "_" + num2str(n) + "deg")), ...
        elevations, ...
        UniformOutput=false)');
% disp(sorted_file_names)

wavelengths = [];
transmissions = [];
for f = sorted_file_names'
    [w, t] = utilities.readModtranFile(char(data_path + f));
    wavelengths = [wavelengths, w(~isnan(w))];
    transmissions = [transmissions, t(~isnan(t))];
end
[sky_transmission, headings] = environment.allSkyTransmission(transmissions, wavelengths(:, 1), elevations);

Extrema = @(arr) [min(arr), max(arr)];
InRange = @(value, bounds) all([any(value >= bounds), any(value <= bounds)]);
Iota = @(x) linspace(0, x, x+1);
Take = @(arr, choices) arr(choices);
IndexOfWavelength = @(wvls, choice) Take(Iota(numel(wvls)), wvls == choice) * InRange(wvls, Extrema(wvls));
DataAtWavelength = @(data, wvls, choice) squeeze(data(IndexOfWavelength(wvls, choice), :, :));
% Picking an example wavelength of 600nm we can then plot the result.

tmp_size = [numel(brightness_data.Wavelengths), size(squeeze(sky_transmission(1, :, :)))];
transmission_at_wavelength = zeros(tmp_size);
for i = 1:numel(brightness_data.Wavelengths)
    wvl = brightness_data.Wavelengths(i);
    transmission_at_wavelength(i, :, :) = ...
        DataAtWavelength(sky_transmission, wavelengths(:, 1), wvl);
end

mapped_transmission = environment.mapToEnvironment( ...
    headings,                   ...
    elevations,                 ...
    transmission_at_wavelength, ...
    sky_headings,               ...
    sky_elevations,             ...
    "Wavelengths",              brightness_data.Wavelengths ...
);

env = environment.Environment( ...
    sky_headings,                ...
    sky_elevations,              ...
    brightness_data.Wavelengths, ...
    mapped_night_sky,            ...
    mapped_transmission          ...
);


%% Simulation
if scheme == "uplink"
    qeyssat = nodes.Satellite( ...
        qeyssat_telescope, ...
        'KeplerElements', [ ...
            6921000, ...
            0,       ...
            97.6,    ...
            167.4,   ...
            98.9170, ...
            60       ...
        ], ...
        'startTime',  start_time,        ...
        'stopTime',   stop_time,         ...
        'sampleTime', 1,                 ...
        'Name',       'QEYSSat',         ...
        'Camera',     uplink_camera,     ...
        'Detector',   MPD_BB84_detector  ...
    );
    simulation = nodes.QkdPassSimulation( ...
        qeyssat, ...
        hogs, ...
        protocol.bb84(), ...
        Environment=env ...
    );
    QKD_figure = simulation.plotResult( ...
        qeyssat, ...
        hogs, ...
        "mask", "Elevation" ...
    ); 
else
    qeyssat = nodes.Satellite( ...
        qeyssat_telescope, ...
        'KeplerElements', [ ...
            6921000, ...
            0,       ...
            97.6,    ...
            167.4,   ...
            98.9170, ...
            60       ...
        ], ...
        'startTime',  start_time,        ...
        'stopTime',   stop_time,         ...
        'sampleTime', 1,                 ...
        'Name',       'QEYSSat',         ...
        'Camera',     uplink_camera,     ...
        'Source',   source               ...
    );
end

if scheme == "uplink"

else
    simulation = nodes.QkdPassSimulation( ...
        hogs, ...
        qeyssat, ...
        protocol.bb84(), ...
        Environment=env ...
    );
    QKD_figure = simulation.plotResult( ...
        hogs, ...
        qeyssat, ...
        "mask", "Elevation" ...
    );
end

headers = { ...
    'Elevation', ...
    'Geometric', ...
    'Optical', ...
    'APT', ...
    'Turbulence', ...
    'Atmospheric',
};
data = [ ...
    simulation.elevation' ...
    simulation.losses.geometric.values' ...
    simulation.losses.optical.values' ...
    simulation.losses.apt.values' ...
    simulation.losses.turbulence.values' ...
    simulation.losses.atmospheric.values' ...
];
file_name = strjoin([ ...
    string(pass_time), ...
    '-', ...
    string(max(simulation.elevation)), ...
    '.csv'
],'');
writetable( ...
    array2table(data, 'VariableNames', headers), ...
    file_name ...
);


% for date = i:length(dates)
%     disp(dates(date))
%     max_elevations = [];
% 
%     start_time = dates(date) - 0.5 / 2;
%     stop_time = dates(date) + 0.5 / 2;
% 
%     if scheme == "uplink"
%         qeyssat = nodes.Satellite( ...
%             qeyssat_telescope, ...
%             'KeplerElements', [ ...
%                 6921000, ...
%                 0,       ...
%                 97.6,    ...
%                 167.4,   ...
%                 98.9170, ...
%                 60       ...
%             ], ...
%             'startTime',  start_time,        ...
%             'stopTime',   stop_time,         ...
%             'sampleTime', 1,                 ...
%             'Name',       'QEYSSat',         ...
%             'Camera',     uplink_camera,     ...
%             'Detector',   MPD_BB84_detector  ...
%         );
%     else
%         qeyssat = nodes.Satellite( ...
%             qeyssat_telescope, ...
%             'KeplerElements', [ ...
%                 6921000, ...
%                 0,       ...
%                 97.6,    ...
%                 167.4,   ...
%                 98.9170, ...
%                 60       ...
%             ], ...
%             'startTime',  start_time,        ...
%             'stopTime',   stop_time,         ...
%             'sampleTime', 1,                 ...
%             'Name',       'QEYSSat',         ...
%             'Camera',     uplink_camera,     ...
%             'Source',   source               ...
%         );
%     end
% 
%     if scheme == "uplink"
%         simulation = nodes.QkdPassSimulation( ...
%             qeyssat, ...
%             hogs, ...
%             protocol.bb84(), ...
%             Environment=env ...
%         );
%         QKD_figure = simulation.plotResult( ...
%             qeyssat, ...
%             hogs, ...
%             "mask", "Elevation" ...
%         );    
%     else
%         simulation = nodes.QkdPassSimulation( ...
%             hogs, ...
%             qeyssat, ...
%             protocol.bb84(), ...
%             Environment=env ...
%         );
%         QKD_figure = simulation.plotResult( ...
%             hogs, ...
%             qeyssat, ...
%             "mask", "Elevation" ...
%         );
%     end
%     disp(max(simulation.elevation))
%     % max_elevations = [max_elevations, max(simulation.elevation)];
% end

% [M,I] = max(max_elevations);
% disp(dates(I))

rmpath(genpath(qrackling_dir))
