function qeyssat = QEYSSAT()
%% a function which returns a satellite model for the canadian SatQKD
% mission QEYSSAT

%% source
QEYSSAT_Source = components.Source(785,...
                                   'MPN_Signal',0.8,...
                                   'MPN_Decoy',0.3,...
                                   'Probability_Signal',0.5,...
                                   'Probability_Decoy',0.25,...
                                   'Repetition_Rate',1E8,...
                                   'Efficiency',1,...
                                   'State_Prep_Error',0.0025);
%% Primary telescope
QEYSSAT_Primary_Telescope = components.Telescope(0.25,...
                                      'Optical_Efficiency',1,...
                                      'Focal_Length',2.72,...
                                      'Pointing_Jitter',1E-6);

%% downlink beacon
QEYSSAT_Downlink_Beacon_Telescope = components.Telescope(0.01,...
                                                         'Wavelength',685,...
                                                         'FOV',0.4,...
                                                         'Pointing_Jitter',1E-3);
QEYSSAT_Downlink_Beacon = beacon.Gaussian_Beacon(QEYSSAT_Downlink_Beacon_Telescope, ...
                                        2,...
                                        685);

%% uplink beacon camera
QEYSSAT_Uplink_Camera_Telescope = components.Telescope(0.08,...
                                                       'Focal_Length',0.86,...
                                                       'Pointing_Jitter',1E-3);
QEYSSAT_Uplink_Beacon_Camera = beacon.Camera(QEYSSAT_Uplink_Camera_Telescope,...
                                             'Wavelength',850);

%% satellite
qeyssat = nodes.Satellite(QEYSSAT_Primary_Telescope,...
                          'Source',QEYSSAT_Source,...
                          'Beacon',QEYSSAT_Downlink_Beacon,...
                          'Camera',QEYSSAT_Uplink_Beacon_Camera,...
                          'semiMajorAxis', 6921000,...
                          'eccentricity',0,...
                          'inclination',97.6,...
                          'rightAscensionOfAscendingNode',171,...
                          'argumentOfPeriapsis',98.9170,...
                          'trueAnomaly',60,...
                          'StartTime',datetime(2035,4,30,16,0,0),...
                          'StopTime',datetime(2035,4,31,4,0,0),...
                          'SampleTime',seconds(1),...
                          'Name','QEYSSAT');